### ISSUE TITLE
SockJS cross-domain communication not supported for all transports

### ISSUE THREAD

**Issue by leolux** [bdecoste/vert.x#1]
As stated in the philosophy of the SockJS project http://sockjs.org (https://github.com/sockjs/sockjs-client): 
"All the transports must support cross domain connections out of the box. It's possible and recommended to host a SockJS server on a different server than your main web site."

This is not true for the SockJS server implementation of Vert.x because it does not support cross-domain communication for all transports. Client browsers produce error messages because of missing CORS headers.

I think the problem is that the CORS header (Access-Control-Allow-Origin: *) in the implementation of the class org.vertx.java.core.sockjs.impl.BaseTransport is only set when the origin of the request is empty. As far as I understood the philosophy of SockJS this CORS header must be set for all requests matching the sockjs appplication prefix.

The missing CORS header results in browser error messages from clients connecting from different domains. Chrome for example produces the following error message:
"XMLHttpRequest cannot load http://my-hostname/eventbus/info. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 404."

There is a difference to other sockjs server implementations like sockjs-netty for example. See https://github.com/cgbystrom/sockjs-netty/blob/master/src/main/java/com/cgbystrom/sockjs/transports/BaseTransport.java

**Comment by ymsoftware** [comment]
Has this been resolved?

**Comment by leolux** [comment]
Yes and v3 comes with an CORS handler out of the box: https://github.com/vert-x3/vertx-web/blob/master/src/main/asciidoc/java/index.adoc#cors-handling

**Comment by ymsoftware** [comment]
Yes, I had problems with milestone 6. It works fine now.

**Comment by 2wings** [comment]
That's great~!Problem resolved
